### PR TITLE
improve: add some hint when can't find macOS version in macos-release

### PR DESCRIPTION
**Pull request by yoa1226**

### CODE REVIEW

**Comment by yoa1226** [comment]
@sindresorhus  Can you review my code when you in free?

**Comment by sindresorhus** [comment]
I don't think this is a good idea. This will just create annoying output and in many cases, the dependency may be many levels down in the dependency tree and outside the control of the user.

We could maybe use `util.debuglog`, but not sure how useful that would be.

**Comment by yoa1226** [comment]
When I run my code, I get error below.
```javascript
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
at macosRelease (node_modules/macos-release/index.js:26:26)
```
I think it's not clear and friendly to developer. It's spend some times to  resolve this problem. I think it's useful to add some hints.

My env list:
macOS: 12.6
macos-release : 2.4.1

**Comment by yoa1226** [comment]
In addition, I can't find `util.debuglog` in macos-release.

**Comment by sindresorhus** [comment]
You're on an old version of this package. I no longer throws on unknown macOS version.

**Comment by sindresorhus** [comment]
> In addition, I can't find util.debuglog in macos-release.

This is a Node.js built-in.

**Comment by sindresorhus** [comment]
I'm going to close this as I don't think it's a good idea.

**Pull request closed without merging**
